commitish: 'master-build'
template: |
  ### Don't forget to prepare the release:

  - Wait for all GitHub actions to finish.
  - Select the `master-build` branch as the target to tag.

  ## What’s Changed

  $CHANGES
