name: Build release package

on:
  release:
    types:
      - published

jobs:
  build-release-package:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin repository
        uses: actions/checkout@v4
        with:
          path: maarten-bday-2025/
          fetch-depth: 1
      - name: Generate zip file
        run: |
          zip -r maarten-bday-2025-${{ github.event.release.tag_name }}.zip maarten-bday-2025
      - name: Upload zip to release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./maarten-bday-2025-${{ github.event.release.tag_name }}.zip
          asset_name: maarten-bday-2025-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
