name: Build & test

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request_target:
    branches:
      - 'master'
      - 'main'

jobs:
  php:
    name: PHP test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-test-command:
          - test:composer
          - test:phpcs
          - test:phpstan
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, dom, simplexml
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          path: maarten-bday-2025/
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Debugging
        run: |
          php --version
          php -m
          composer --version
          ls -lsah
      - name: Composer install
        run: |
          cd maarten-bday-2025/
          composer install --prefer-dist
      - name: ${{ matrix.php-test-command }}
        run: |
          cd maarten-bday-2025/
          composer run ${{ matrix.php-test-command }}
  npm:
    name: NPM test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        npm-test-command:
          - lint
          - build
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Debugging
        run: |
          node -v
          npm -v
      - name: NPM Install
        run: |
          npm ci
      - name: ${{ matrix.npm-test-command }}
        run: |
          npm run ${{ matrix.npm-test-command }} --if-present
      - name: ${{ matrix.npm-test-command }}
        run: |
          npm run ${{ matrix.npm-test-command }} --if-present
