name: Build & test

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request_target:
    branches:
      - 'master'
      - 'main'

jobs:
  php:
    name: PHP test
    runs-on: ubuntu-latest
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, dom, simplexml
      - uses: actions/checkout@v4
        with:
          path: maarten-bday-2025/
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Debugging
        run: |
          php --version
          php -m
          composer --version
          ls -lsah
      - name: Composer build
        run: |
          cd maarten-bday-2025/
          composer install --prefer-dist
      - name: test:composer
        run: |
          cd maarten-bday-2025/
          composer run test:composer
      - name: test:phpcs
        run: |
          cd maarten-bday-2025/
          composer run test:phpcs
      - name: test:phpstan
        run: |
          cd maarten-bday-2025/
          composer run test:phpstan
